<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ArticleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('articles')->insert([
            'title'=>'测试数据',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
        DB::table('articles')->insert([
            'title'=>'测试数据2',
            'cover'=>'/images/2.png',
            'type_id'=>1,
            'content'=>'123',
            'user_id'=>1,
            'display'=>1
        ]);
    }
}
